spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotlin_study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  exposed:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.jdbc: debug
    Exposed: debug
#    org.hibernate.type: trace
